#### 1. What is a Python library? Why do we use Python libraries?

- A python libary is a collection of pre-written code that can be used to perfrom various tasks, ranging from simple operations to complex algorithms and processes. 
- kLibraries consist of modules, whcih are files containing python code that can be importted and utilized in python programs

Use Cases

1) Code Reusability 
-> Libraries provide reusable code, whcih means we don't have to write code from scratch
-> That helps in speeding up the development process

2) Efficiency 
-> Using libraries allows you to implement complex functionalities without needing to understanding underlying code, making development faster and more efficient 

3) Standardization 
-> Libraries are often well trusted and standardized, reducing the likelihood of bugs and errors in code

4) Wide Functionality 
-> Python Libraries offer a wide range of functionalities, from data manipulation, machine learning, web development, to scientific computing. 

#### 2. What is the Difference between Numpy array and List?

1) Data Type Consistency
-> Numpy array: Homogeneous, meaning all elements in a numpy array must be of the same data type
-> Python List: Haterogeneous, meaning elements can be of different data types

2) Performance 
-> Numpy array: Much faster in operations due to its underlying C implementation and contiguous memory allocation 
-> Python List: Slower in performance because of the flexibility to hold different data types and the overhead of python's dynamic typing 

3) Memory Efficiency 
-> Numpy array: More memory efficient since it store data in a contiguous block of memory and the element are of the same type 
-> Python List: less memory efficient because it stores reference to the actual objects, which can be of different types

4) Mathematical Operations:
-> Numpy array supports element wise operations which means we can perform operations on the entire array without looping
-> Python list requires looping for element wise operations, whcih can be slower and more difficult to write 

5) Functionality
-> Numpy array comes rich set of mathematical functions specifically designed for array operations 
-> python list lack built-in support for advanced mathematical operations. 

6) Resizing 
-> numpy array fixed size after creation, resizing requires creating a new array and copying the data 
-> python list is dynamic in size, allowing for easy appending, insertion and removal of elements 

7) Indexing and Slicing 
-> Numpy array supports advanced slicing and multi-dimensional indexing, making it ideal for woking with multi-dimensional data 
-> Python list supports basic slicing and indexing but it is less powerful compared to numpy array when dealing with multi-dimensional data.

#### 3. Find the shape, size and dimension of the following array?

- [[1, 2, 3, 4]
- [5, 6, 7, 8],
- [9, 10, 11, 12]]

In [1]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

dimension = array.ndim
print("Dimension of Array is ",dimension)

Dimension of Array is  2


#### 4. Write python code to access the first row of the following array?

In [2]:
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

array[0]

array([1, 2, 3, 4])

#### 5. How do you access the element at the third row and fourth column from the given numpy array?

In [3]:
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

array[2][3]

12

#### 6. Write code to extract all odd indexed elements from the given numpy array?

In [4]:
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

odd_index_elements = array[1::2, 1::2]

print("Odd-indexed elements:")
print(odd_index_elements)


Odd-indexed elements:
[[6 8]]


#### 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [5]:
import numpy as np 

random_matrix = np.random.rand(3,3)
random_matrix

array([[0.87383761, 0.35632525, 0.93097927],
       [0.18700993, 0.8645689 , 0.22936598],
       [0.78200536, 0.72676903, 0.76225124]])

##### 8. Describe the difference between np.random.rand and np.random.randn?

1) Distribution:
- np.random.rand generates random numbers from a uniform distribution over the interval [0,1). This means each number is equally likely to be anywhere between 0 and 1 
- np.random.randn generates random numbers from a standard normal distribution with a mean of 0 and a standard deviation of 1. This means numbers are spread around the mean, with values potentially being negative of positive 

2) Range of values 
- np.random.rand produces value in the range [0,1), meaning number are between 0 inclusive and 1 exclusive.
- np.random.randn produces values that can range from negative to positive infinity centered around 0

3) Function Signature;
- np.random.rand creates an array of the specified shape with values from a uniform distribution 
- np.random.randn creates an array of the specified shape with values from a standard normal distribution 

4) Use case:
- np.random.rand ideal for scenarios requiring uniformly distributed random numbers, such as initializing random weights or generating random probabilities 
- np.random.randn suitable for scenarios requiring normally distributed data such as simulations and statistical modelling

#### 9. Write code to increase the dimension of the following array? 

In [6]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
expanded_array = np.expand_dims(array, axis=0) 

In [7]:
array.shape

(3, 4)

In [8]:
expanded_array.shape

(1, 3, 4)

#### 10. How to transpose the following array in NumPy?

In [9]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
array.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [10]:
array.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

#### 11. Consider the following matrix:
#### Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
#### Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

In [11]:
A = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

B = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])


In [12]:
# 1) index wise multiplication

In [13]:
A*B

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [14]:
# 2) Matix multiplication
np.dot(A,B.T)

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [15]:
# 3) Add both the matrics 
A+B

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [16]:
# 4) Subtract matrix B from A 
B-A

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [17]:
# Divide Matrix B by A
B/A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### 12. Which function in Numpy can be used to swap the byte order of an array?

In NumPy, you can use the byteswap() function to swap the byte order (endianness) of an array. This is useful when working with data that has a different byte order from the one expected by your system.

Swaps the byte order of the array elements. This function is often used when dealing with binary data files that may have been written in a different byte order.

In [18]:
import numpy as np

array = np.array([1, 256, 65536], dtype=np.int16)  # Using 16-bit integers

print("Original array:")
print(array)
print("Original array dtype:", array.dtype)

swapped_array = array.byteswap()

print("Array after byteswap:")
print(swapped_array)
print("Array dtype after byteswap:", swapped_array.dtype)


Original array:
[  1 256   0]
Original array dtype: int16
Array after byteswap:
[256   1   0]
Array dtype after byteswap: int16


#### 13. What is the significance of the np.linalg.inv function?

The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix. Here’s a breakdown of its significance and usage:

Solving linear Systems 
- To solve a system of linear equations represented as A*x = b, we can find the solution vector x by computing x=A-1*b. This means we needfirst compute the inverse of matrix A and then multiply it by the vector b.

Matrix Algebra 
- matrix inversion is used in various algebric operations and transformations. such as optimization and matirx decompositions.


In [19]:
import numpy as np

# Define a square matrix
A = np.array([[1, 2],
              [3, 4]])

# Compute the inverse of the matrix
A_inv = np.linalg.inv(A)

print("Original matrix A:")
print(A)

print("Inverse of matrix A:")
print(A_inv)

identity_matrix = np.dot(A, A_inv)
print("Product of A and its inverse (should be identity matrix):")
print(identity_matrix)


Original matrix A:
[[1 2]
 [3 4]]
Inverse of matrix A:
[[-2.   1. ]
 [ 1.5 -0.5]]
Product of A and its inverse (should be identity matrix):
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


#### 14. What does the np.reshape function do, and how is it used?

- The np.reshape function in NumPy is used to chaneg the shape of an existing array without changing  its data. This function allows you to rearrange the dimensions the dimensions of the array to fit a new shape while preserving the total nimber of elements 

What np.reshape does 
- Changes Shape: np.resha[e modifies the shape of the array to a new specified shape 
- Preserves Data: The data in the array remains the same, only the arrangement of elements is altered 
- Must match size: the new shape must have the same number of elements as the original shape

In [20]:
import numpy as np
array = np.arange(12) 

reshaped_array = np.reshape(array, (2, -1))  # The second dimension is automatically determined
print("initial array:")
print(array)
print("Reshaped array (2x?):")
print(reshaped_array)

initial array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array (2x?):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


#### 15. What is broadcasting in Numpy?

- Broadcasting in NumpPy is a powerful feature that allows you to perform operations on array of different shape in a way that is both different shapes in a way that is both efficeint and intuitive
- It automatically expands the smaler array to match the shape of the larger array so that element-wise operations can be performed

#### Key Concepts of broadcasting 

1) Automatic Expansion 
- Broadcasting enables operations between arrays with different shapes by automatically expanding the dimensions of the smaller array to match the larger one 

2) Dimension Compability 
- For two arrays to be broadcast together, their shapes must be compaitabl. Specifically, they should meet the following conditions 
- When comparing dimensions or the arrays, they must either be the  same or one of them must be 1. if these conditions are not met, broadcasting will not occur, and an error will be raised.

3) Efficiency:
- Broadcasting is performed without creating unnecessary copies of data, making it both memory and computationally efficient

In [21]:
import numpy as np

# Define two arrays
A = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15]])

B = np.array([10, 20, 30, 40, 50])

# Add B to each row of A
result = A + B

print("Array A:")
print(A)

print("Array B:")
print(B)

print("Result of A + B (broadcasting applied):")
print(result)


Array A:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Array B:
[10 20 30 40 50]
Result of A + B (broadcasting applied):
[[11 22 33 44 55]
 [16 27 38 49 60]
 [21 32 43 54 65]]
